### ISSUE TITLE
Bug: Intervention or Survey not correctly saved when creating them first time

### ISSUE THREAD

**Issue by johannesvedder** [hpi-studyu/studyu#526] opened 2023-11-14 16:27 UTC
Bug seems to occur on all branches, including `main` ([https://designer.studyu.health](https://designer.studyu.health))

### Steps to reproduce:

- Create a new study
- Give that study a name
- Go to Intervention
- Add a new intervention, modify the title and fill out the description
- Add a intervention task, fill out title
- Save both
- Click on "Unnamed intervention". Neither the intervention title nor the intervention description are saved. Only the task is saved correctly.

The same happens with a new measurement survey. After the bug occured once, it does not happen anymore.

### Solution

Seems to be related to https://github.com/hpi-studyu/studyu/blob/dev/designer_v2/lib/features/study/study_test_controller.dart

Removing all occurences of `studyTestControllerProvider` solves the issue ([here](https://github.com/hpi-studyu/studyu/blob/dev/designer_v2/lib/features/study/study_test_frame.dart#L83) and [here](https://github.com/hpi-studyu/studyu/blob/dev/designer_v2/lib/features/study/study_test_frame.dart#L87))

**Comment by hig-dev** [comment] 2023-11-15 02:15
Here are the minimal steps to reproduce.

### Steps to reproduce:

- Create a new study
- Give that study a name
- Go to Intervention
- Add a new intervention, modify the title
- Save
- Click on "Unnamed intervention". The intervention title is not saved.

I found the root cause for this bug. It has something to do with the instances of InterventionFormViewModel. Multiple instances of InterventionFormViewModel are created and the ReactiveTextField updates instance A, but the save function saves the data from instance B which was not updated. I am investigating this further to find a fix for this bug.

**Comment by hig-dev** [comment] 2023-12-16 13:59
I think this issue is related to https://github.com/joanpablo/reactive_forms/issues/262

**Closed** 2024-07-01 16:46 UTC
Labels: designer_v2
